# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call('echo_rcpp_hello_world', PACKAGE = 'echo')
}

str_reverse <- function(str) {
    .Call('echo_str_reverse', PACKAGE = 'echo', str)
}

